### ISSUE TITLE
Publish as Firefox addon

### ISSUE THREAD

**Issue by wtf403** [harrisondeo/FlexHeader#4]
Hi great extension! Could you also publish it to [addons.mozilla.org](https://addons.mozilla.org/en-US/developers/addon/submit/) ?

**Comment by harrisondeo** [comment]
hey @wtf403, I have reopened the issue because the version I published to the addons store for Mozilla didnt work and needs some more tweaking

**Comment by wtf403** [comment]
Yep, noticed this. Thank you! 💚

**Comment by harrisondeo** [comment]
Changes made and uploaded to firefox addon store:
https://addons.mozilla.org/en-GB/firefox/addon/flexheaders-alter-http-headers/
