### ISSUE TITLE
Tabs are hard to navigate when there are many pages or page titles are long

### ISSUE THREAD

**Issue by reccanti** [harrisondeo/FlexHeader#5]
When there are several pages in the extension (more than 5 in my experience), it's hard to see what pages are available. The arrow button helps, but it's kind of hard to see.

In addition, when page names are long, it's hard to see the full name, especially since visible tabs don't get shown after clicking the arrow button.

**Comment by harrisondeo** [comment]
Thank you for the feedback and I do agree, I have worked on a new version (v1.1.0) which I have just uploaded.
If you want to update and let me know how it is for you
